_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 2
                - 3
                - 16
                - 23
                - 24
                - 55
            "4": 3.10.12
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 1
                - 5
            "12": 0.19.2
            "13": linux-x86_64
batch_size:
    value: 8
beta1:
    value: 0.9
beta2:
    value: 0.999
context_size:
    value: 128
eval_interval:
    value: 200
eval_iters:
    value: 20
grad_clip:
    value: 1
hidden_size:
    value: 128
learning_rate:
    value: 0.005
log_interval:
    value: 100
max_iters:
    value: 2401
min_lr:
    value: 0.0005
total_trainable_parameters:
    value: 448584
vocab:
    value: abcdefghijklmnopqrstuvwxyz0123456789 .!?
warmup_iters:
    value: 200
weight_decay:
    value: 0.1
